AWSTemplateFormatVersion: "2010-09-09"
Description: "Create EC2 Instance"

### Parametres ###
Parameters: 
  ImageId: 
    Type: String
    Default: "" 
    Description: "AMI ID for Ec2"
   
  InstanceType: 
    Type: String
    Default: "t2.micro"
    Description: "Instance Type"
    AllowedValues: 
      - t2.micro
      - t2.nano
      - t2.small
  
  SubnetId:
    Type: String 
    Default: ""
    Description: "Subnet for Ec2 Instance" 

  SSHKeyName: 
    Type: String 
    Default: ""
    Description: "SSH Key Name"
  
      
### Resources ###
Resources:
  TestInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType 
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64:
          !Sub |
           #!/bin/bash
           echo "hello" >> /tmp/myfile
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: "20"
      Tags:  
        - Key: "Team"
          Value: "Backend"
        - Key: "Name"
          Value: "Test-EC2-SG" 
      SecurityGroupIds: 
        - sg-08c3b2eedc22cd9c5
      KeyName: !Ref SSHKeyName 

### Outputs ### 
Outputs:
  InstanceName:
    Value: !Ref TestInstance
    Description:  "Inctance ID"
  TestInstancePublicIp:
    Value: !GetAtt TestInstance.PublicIp
    Description: "Instance Public Ip"